Closes #133: Updated documentation and test cases for age unit (#135)
* #133: Updated documentation, warning messages for age unit conversion

* #133: added some test for different age units

* #133: Updated documentation and example for age unit conversion by manual method

* #133: Updates to advs.Rmd

* Increment version number to 0.3.0.9000

* #133: Updated NEWS.md

* #133: styler

* #133: updates for lintr checks

* #133: Styler

* #133: Styler

* #133: Updates to text

* #133: Updated warnings

* #133: Printed the unmatched records and added warning to clarify

* #133: updates for lint

* Update vignettes/advs.Rmd

Co-authored-by: Fanny Gautier <157114584+Fanny-Gautier@users.noreply.github.com>

* Update vignettes/advs.Rmd

Co-authored-by: Fanny Gautier <157114584+Fanny-Gautier@users.noreply.github.com>

* Update vignettes/advs.Rmd

Co-authored-by: Fanny Gautier <157114584+Fanny-Gautier@users.noreply.github.com>

* Update R/derive_params_growth_age.R

Co-authored-by: Fanny Gautier <157114584+Fanny-Gautier@users.noreply.github.com>

* #230: Update Rd file.

* #133: remove here package from list, was added twice.

* Update R/derive_params_growth_age.R

Co-authored-by: Fanny Gautier <157114584+Fanny-Gautier@users.noreply.github.com>

* #133: lint updates

* #133: update WORDLIST

* #133 DESCRIPTION: Update RoxygenNote from 7.3.3 to 8.0.0
💻 Please rerun the following command on your workstation and push your changes
-------------------------
roxygen2::roxygenize('.')
-------------------------
ℹ roxygen2 version that was used in this workflow: ‘8.0.0’
🙏 Please ensure that the 'RoxygenNote' field in the DESCRIPTION file matches this version
Error: Process completed with exit code 1.

* #133 derive_params_growth_age.R: print unmatched records only when it exists

* #133 admiralpeds-package.R: @importFrom must be only 1 line long, not 2.

* #133 fixe CI/CD Links / Validate Links - running document() with roxygen 8.0.0

* #133 vignettes/admiralpeds.Rmd: Update failing link from CI/CD Links / Validate Links workflow

* #133 vignettes/advs.Rmd: Update failing link from CI/CD Links / Validate Links workflow

* #133 vignettes/advs.Rmd: Update failing link from CI/CD Links / Validate Links workflow

* #133 r/derive_params_growth_age.R: Remove #nolint and wrap the line to 80 characters within ## Age Unit Matching section

* #133 documentation

* #133 Remove nolint from WORDLIST

---------

Co-authored-by: Fanny Gautier <157114584+Fanny-Gautier@users.noreply.github.com>
Co-authored-by: Fanny-Gautier <fanny.gautier@cytel.com>